#!/usr/bin/env python3.11
"""Generate the EN Coach guide as .docx.

English counterpart of docs/build_coach_guide.py (FR GUIDE-COACH-PWNZZAI.docx).
Reuses ALL helpers and constants from the FR module; only the prose and the
mermaid labels are restated in English.

    python3.11 docs/build_coach_guide_en.py    # -> GUIDE-COACH-PWNZZAI-EN.docx
"""
from pathlib import Path
import tempfile

import build_coach_guide as c
from docx import Document

DOCS_DIR = c.DOCS_DIR
OUT_EN = DOCS_DIR / "GUIDE-COACH-PWNZZAI-EN.docx"

MERMAID_ARCHI_EN = """
flowchart LR
    B["Student browser<br/>:%COACH%"]
    C["pwnzzai-coach<br/>proxy + API"]
    P["pwnzzai-app<br/>:8080 (OWASP intact)"]
    O["ollama"]
    D["Teacher dashboard<br/>:%DASH%"]
    B -->|"all requests"| C
    C -->|"forwarded as-is"| P
    C -->|"judge + hints"| O
    C -->|"cohort events"| D
    C -. "injects coach.js" .-> B
""".replace("%COACH%", c.COACH_PORT).replace("%DASH%", c.DASHBOARD_PORT)

MERMAID_SEQUENCE_EN = """
sequenceDiagram
    autonumber
    participant E as Student
    participant A as Vulnerable assistant
    participant C as coach
    participant O as Ollama (judge)
    participant D as Teacher dashboard
    E->>A: attack prompts
    A-->>E: replies
    Note over E: coach.js captures the conversation
    E->>C: POST /__coach/judge {transcript}
    C->>O: prompt + few-shot + transcript
    O-->>C: VERDICT / SCORE / REASON
    C-->>E: {success, score, reason}
    E->>C: POST /__coach/event (if solved)
    C->>D: POST /api/sync
"""


def build_en(tmp: Path) -> None:
    doc = Document()
    c.setup_styles(doc)
    c.title_block(
        doc, "JuiceLab Coach for PwnzzAI — Guide",
        "OWASP PwnzzAI + pedagogical layer (LLM judge, hints, cohort tracking)",
    )

    doc.add_heading("1. What the coach adds", level=1)
    c.para(doc, "The JuiceLab Coach turns OWASP PwnzzAI (the deliberately "
                "vulnerable pizza shop for learning LLM security) into a guided, "
                "remotely-tracked lab session, without changing a single line of the "
                "OWASP product.")
    c.para(doc, "It brings JuiceLab's student feature parity through a tabbed sidebar "
                "injected into the browser:")
    c.bullet(doc, "Briefing: mission + pedagogical concepts per lab (bilingual), "
                  "OWASP LLM Top 10 anchors.")
    c.bullet(doc, "Graded hints: 5 levels N1-N5, cost 5/10/20/35/50 %, progressive "
                  "reveal, score penalty. Content generated by the local model, "
                  "adapted to failed attempts.")
    c.bullet(doc, "Before/after Journal and Quiz (3 graded MCQs with explanations).")
    c.bullet(doc, "Automatic judge (LLM-as-judge): verdict + score 0-100 + "
                  "justification, from the captured conversation.")
    c.bullet(doc, "Progress tab (student dashboard): score per lab, hints consumed, "
                  "badges (4 tiers), average score.")
    c.bullet(doc, "Reporting to the JuiceLab teacher dashboard: a PwnzzAI session "
                  "shows up in the same cohort matrix as Juice Shop.")
    c.note(doc, "Scoring (same as JuiceLab): score = max(50, 100 - sum of hint "
                "costs).")

    png_archi = tmp / "archi_en.png"
    c.render_mermaid(MERMAID_ARCHI_EN, png_archi, tmp)
    c.add_diagram(doc, png_archi, "The coach is a sidecar placed in front of "
                                  "PwnzzAI; the OWASP image stays intact.")

    doc.add_heading("2. What gets installed", level=1)
    c.add_table(
        doc, ["Container", "Port", "Role"],
        [
            ["pwnzzai-coach", c.COACH_PORT, "Student entry: proxy + coach panel"],
            ["pwnzzai-shop", c.RAW_PORT, "Raw OWASP PwnzzAI (intact, debug)"],
            ["ollama", "internal", "Labs model + judge/hints model"],
        ],
        [45, 25, 100],
    )
    c.note(doc, "The student only uses http://localhost:" + c.COACH_PORT +
                ". Port " + c.RAW_PORT + " stays available to debug PwnzzAI without "
                "the coach.")

    doc.add_heading("3. Installation", level=1)
    c.para(doc, "Self-contained stack (PwnzzAI cloned at build). From the repo root:")
    c.code_block(doc, [
        "cp .env.example .env    # cohort + dashboard",
        "docker compose up -d --build",
    ])
    c.para(doc, "Then pull the Ollama models (PwnzzAI Basics page, or CLI):")
    c.code_block(doc, [
        "docker exec ollama ollama pull llama3.2:1b   # labs model",
        "docker exec ollama ollama pull " + c.JUDGE_MODEL + "   # judge model",
    ])
    c.para(doc, "Check everything responds:")
    c.code_block(doc, [
        "curl -s http://localhost:" + c.COACH_PORT + "/__coach/health",
        '# {"ok":true,"ollama":true,"dashboard_configured":true}',
    ])

    doc.add_heading("4. Connecting to the teacher dashboard (the cohort)", level=1)
    c.para(doc, "Topology: one central dashboard, PwnzzAI is a client. The teacher "
                "dashboard is a single shared instance, deployed once on the juicelab "
                "side. It serves both JuiceLab (Juice Shop) cohorts AND PwnzzAI "
                "cohorts: both report into the same matrix.")
    c.para(doc, "PwnzzAI NEVER duplicates the dashboard server code. It plugs in as a "
                "client via the JUICELAB_DASHBOARD_URL variable. Anti-pattern to "
                "avoid: deploying a second PwnzzAI-specific dashboard.")
    c.para(doc, "Optional case: if the central dashboard does not exist yet and you "
                "want to deploy it from this machine, scripts/deploy-dashboard.sh "
                "does a pinned sparse-checkout of the juicelab repo (REF set by "
                "JUICELAB_DASHBOARD_REF, SHA advised in prod) and pulls ONLY the "
                "teacher part (dashboard/, docker/, scripts/). The overlay and the "
                "student Juice Shop are never pulled. Once the dashboard is up, point "
                "JUICELAB_DASHBOARD_URL at it.")
    c.add_screenshot(
        doc, c.IMG_DIR / "prof-dashboard-light.png",
        "Teacher dashboard - PwnzzAI cohort on the central instance (same matrix "
        "as the Juice Shop cohorts).")
    c.para(doc, "Everything is configured in PwnzzAI's .env file:")
    c.add_table(
        doc, ["Variable", "Role", "Example"],
        [
            ["JUICELAB_DASHBOARD_URL", "Dashboard URL as seen from the container",
             "http://host.docker.internal:" + c.DASHBOARD_PORT],
            ["JUICELAB_COHORT_ID", "Cohort id", c.COHORT],
            ["JUICELAB_INSTANCE_LABEL", "Student machine name in the matrix", c.LABEL],
            ["COACH_JUDGE_MODEL", "Ollama model for judge/hints", c.JUDGE_MODEL],
        ],
        [60, 75, 55],
    )
    c.note(doc, "Dashboard on the same machine: use host.docker.internal (not "
                "127.0.0.1). Remote dashboard: set the teacher's IP. Empty = local "
                "mode with no reporting. The dashboard registers the student "
                "automatically on the first event.")
    c.para(doc, "After editing .env, recreate the coach container:")
    c.code_block(doc, [
        "docker compose up -d pwnzzai-coach",
    ])

    doc.add_heading("5. Student side: how it is used", level=1)
    c.note(doc, "The coach panel is CLOSED at first, it does not appear on its own. "
                "To open it: click the round purple JL button at the bottom right, "
                "OR append #coach to a lab URL (e.g. http://localhost:" + c.COACH_PORT
                + "/direct-prompt-injection#coach), which opens the panel "
                "automatically. Make sure you are on port " + c.COACH_PORT + " (the "
                "coach), not the raw app. If nothing shows: Ctrl+Shift+R.")
    c.add_screenshot(doc, c.IMG_DIR / "coach-closed.png",
                     "The closed JL button, bottom right of the lab page.")
    c.add_screenshot(doc, c.IMG_DIR / "coach-panel.png",
                     "The open panel: Briefing / Hints / Journal / Quiz / Progress tabs.")
    c.para(doc, "Hints tab - the graded ladder: N1 -5 %, N2 -10 %, N3 -20 %, N4 "
                "-35 %, N5 -50 %. Progressive reveal (N+1 stays greyed until N is "
                "taken); each hint lowers the lab score, which never drops below "
                "50/100 (score = max(50, 100 - sum of costs)). Content generated by "
                "the local model, adapted to failed attempts (N1 = nudge, N5 = "
                "near-complete example).")
    c.add_screenshot(doc, c.IMG_DIR / "coach-hints.png",
                     "Hints tab: 5 graded levels -5/-10/-20/-35/-50 %.")
    c.para(doc, "Progress tab - the student summary: 'Check my success' button "
                "(submits the conversation to the judge), score per lab, average "
                "score out of 100, solved labs and the 4 badges. This is also where "
                "the student joins a cohort (field at the bottom, with their email; "
                "the teacher then approves the request).")
    c.add_screenshot(doc, c.IMG_DIR / "coach-progress.png",
                     "Progress tab: score, badges, join a cohort.")
    c.numbered(doc, "Open http://localhost:" + c.COACH_PORT +
                    " and go to a lab (e.g. Direct Prompt Injection).")
    c.numbered(doc, "Click the round purple JL button at the bottom right: the "
                    "tabbed coach panel opens (FR/EN button).")
    c.numbered(doc, "5 tabs: Briefing (mission + concepts), Hints (5 levels N1-N5 "
                    "with increasing cost), Journal (before/after), Quiz (3 MCQs), "
                    "Progress (judge, score, badges).")
    c.numbered(doc, "Attack the assistant as usual: the conversation is captured "
                    "automatically.")
    c.numbered(doc, "Stuck? The Hints tab reveals a graded tip (N1 = nudge, N5 = "
                    "near-complete example); each hint lowers the score (floor 50).")
    c.numbered(doc, "'Check my success' (Progress tab) submits the conversation to "
                    "the judge: Solved / Partial / Not yet + score + justification; "
                    "a success can unlock a badge.")
    c.note(doc, "Teacher tip: a link ending with #coach (e.g. http://localhost:" +
                c.COACH_PORT + "/indirect-prompt-injection#coach) opens the panel "
                "automatically.")

    doc.add_heading("6. Teacher side: what is reported", level=1)
    c.para(doc, "The coach sends these events via the public POST /api/sync contract "
                "(the same as Juice Shop):")
    c.add_table(
        doc, ["Event", "Trigger", "Data"],
        [
            ["session_start", "opening a lab page", "path, identity if detected"],
            ["hint_revealed", "revealing a hint", "level N1-N5, cost, score"],
            ["challenge_solved", "judge -> Solved", "score, verdict, justification"],
            ["journal_filled", "Journal after save", "length, text"],
            ["quiz_completed", "quiz validation", "score, correct / total"],
            ["badge_earned", "badge unlocked", "badge id"],
        ],
        [45, 60, 65],
    )

    png_seq = tmp / "sequence_en.png"
    c.render_mermaid(MERMAID_SEQUENCE_EN, png_seq, tmp)
    c.add_diagram(doc, png_seq, "From transcript to judge verdict, then reported to "
                                "the dashboard if solved.")

    doc.add_heading("7. Choosing the judge model", level=1)
    c.add_table(
        doc, ["Model", "Verdict", "Recommendation"],
        [
            ["llama3.2:1b", "unreliable (inconsistent)", "avoid for the judge"],
            ["llama3.2:3b", "reliable on clear-cut cases", "advised minimum"],
            ["mistral:7b / llama3.1:8b", "reliable on subtle cases",
             "ideal if the machine can handle it"],
        ],
        [50, 60, 60],
    )
    c.note(doc, "The judge model is independent from the labs' model: labs on 1b "
                "(fast) and judge on 3b (reliable) on the same machine. Set via "
                "COACH_JUDGE_MODEL.")

    doc.add_heading("8. Troubleshooting", level=1)
    c.add_table(
        doc, ["Symptom", "Cause", "Fix"],
        [
            ["Coach service unavailable", "no judge model pulled",
             "ollama pull " + c.JUDGE_MODEL],
            ["health: ollama false", "same", "pull a model, check COACH_JUDGE_MODEL"],
            ["Inconsistent verdicts", "model too small (1b)", "move to 3b or larger"],
            ["Dashboard not configured", "empty URL", "set the URL, recreate the container"],
            ["Nothing is reported", "dashboard unreachable from the container",
             "host.docker.internal, port/firewall"],
            ["Port " + c.COACH_PORT + " taken", "another service",
             "change the mapping in docker-compose.coach.yml"],
        ],
        [50, 55, 65],
    )

    doc.add_heading("9. Why it resists OWASP changes", level=1)
    c.para(doc, "The proxy knows none of PwnzzAI's internal routes: it forwards "
                "everything and only injects a script tag. Capture is generic (any "
                "fetch/XHR POST carrying a text field). If OWASP renames a route or "
                "changes a page's style, the coach keeps working; only labs.json may "
                "need a path update for lab detection.")

    doc.save(str(OUT_EN))
    print(f"  [ok] {OUT_EN.name} generated ({OUT_EN.stat().st_size // 1024} Ko)")


def main() -> None:
    print("Generating the EN JuiceLab Coach guide for PwnzzAI...")
    with tempfile.TemporaryDirectory(dir=str(DOCS_DIR)) as td:
        build_en(Path(td))
    print("Done.")


if __name__ == "__main__":
    main()
